# Generated by scripts/generate_control_specs.py. Do not edit by hand.

DEVICE_SPECS = {
    1: {'key': 'turntable', 'name': 'RS422 转台'},
    2: {'key': 'camera', 'name': '相机'},
}

COMMAND_SPECS = {
    1: {
        1: {'key': 'enable', 'name': '使能控制', 'category': '', 'params': [{'key': 'enabled', 'type': 'uint8', 'values': {0: 'disable', 1: 'enable'}}]},
        2: {'key': 'position', 'name': '位置指向模式', 'category': '', 'params': [{'key': 'azimuth', 'type': 'int32_be', 'min': -360, 'max': 360, 'scale': 10000}, {'key': 'pitch', 'type': 'int32_be', 'min': -90, 'max': 90, 'scale': 10000}]},
        3: {'key': 'jog', 'name': '位置点动模式', 'category': '', 'params': [{'key': 'azimuthDelta', 'type': 'int32_be', 'min': -360, 'max': 360, 'scale': 10000}, {'key': 'pitchDelta', 'type': 'int32_be', 'min': -360, 'max': 360, 'scale': 10000}]},
        4: {'key': 'speed', 'name': '速度模式', 'category': '', 'params': [{'key': 'azimuthSpeed', 'type': 'int32_be', 'min': -838.8608, 'max': 838.8607, 'scale': 10000}, {'key': 'pitchSpeed', 'type': 'int32_be', 'min': -838.8608, 'max': 838.8607, 'scale': 10000}]},
    },
    2: {
        257: {'key': 'laser_standby', 'name': '激光待机', 'category': 'laser', 'params': []},
        258: {'key': 'laser_single_measure', 'name': '激光单次测距', 'category': 'laser', 'params': []},
        259: {'key': 'laser_continuous_measure', 'name': '激光连续测距', 'category': 'laser', 'params': [{'key': 'periodMs', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        260: {'key': 'laser_self_test', 'name': '激光自检', 'category': 'laser', 'params': []},
        261: {'key': 'laser_set_nearest_distance', 'name': '激光设置最近距离', 'category': 'laser', 'params': [{'key': 'distanceM', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        262: {'key': 'laser_query_shot_count', 'name': '激光累计出光次数查询', 'category': 'laser', 'params': []},
        263: {'key': 'laser_set_farthest_distance', 'name': '激光设置最远距离', 'category': 'laser', 'params': [{'key': 'distanceM', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        264: {'key': 'laser_apd_power_on', 'name': '激光 APD 电源开', 'category': 'laser', 'params': []},
        265: {'key': 'laser_apd_power_off', 'name': '激光 APD 电源关', 'category': 'laser', 'params': []},
        266: {'key': 'laser_set_work_timeout', 'name': '激光连续工作超时时间设置', 'category': 'laser', 'params': [{'key': 'timeoutMin', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        267: {'key': 'laser_query_id', 'name': '激光编号查询', 'category': 'laser', 'params': []},
        513: {'key': 'lens_zoom_in', 'name': '镜头变倍+', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        514: {'key': 'lens_zoom_out', 'name': '镜头变倍-', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        515: {'key': 'lens_focus_plus', 'name': '镜头聚焦+', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        516: {'key': 'lens_focus_minus', 'name': '镜头聚焦-', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        517: {'key': 'lens_iris_plus', 'name': '镜头光圈+', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        518: {'key': 'lens_iris_minus', 'name': '镜头光圈-', 'category': 'lens', 'params': [{'key': 'speed', 'type': 'uint8', 'min': 1, 'max': 63}]},
        519: {'key': 'lens_relay_on', 'name': '镜头继电器开', 'category': 'lens', 'params': [{'key': 'relayId', 'type': 'uint8', 'min': 1, 'max': 8}]},
        520: {'key': 'lens_relay_off', 'name': '镜头继电器关', 'category': 'lens', 'params': [{'key': 'relayId', 'type': 'uint8', 'min': 1, 'max': 8}]},
        521: {'key': 'lens_set_preset', 'name': '镜头设置预置位', 'category': 'lens', 'params': [{'key': 'presetId', 'type': 'uint8', 'min': 1, 'max': 255}]},
        522: {'key': 'lens_call_preset', 'name': '镜头调用预置位', 'category': 'lens', 'params': [{'key': 'presetId', 'type': 'uint8', 'min': 1, 'max': 255}]},
        523: {'key': 'lens_query_zoom', 'name': '镜头查询变倍位置', 'category': 'lens', 'params': []},
        524: {'key': 'lens_query_focus', 'name': '镜头查询聚焦位置', 'category': 'lens', 'params': []},
        525: {'key': 'lens_query_iris', 'name': '镜头查询光圈位置', 'category': 'lens', 'params': []},
        526: {'key': 'lens_goto_zoom', 'name': '镜头变倍到指定位置', 'category': 'lens', 'params': [{'key': 'position', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        527: {'key': 'lens_goto_focus', 'name': '镜头聚焦到指定位置', 'category': 'lens', 'params': [{'key': 'position', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        528: {'key': 'lens_goto_iris', 'name': '镜头光圈到指定位置', 'category': 'lens', 'params': [{'key': 'position', 'type': 'uint16_be', 'min': 0, 'max': 65535}]},
        529: {'key': 'lens_stop', 'name': '镜头停止', 'category': 'lens', 'params': []},
    },
}

DEVICE_TURNTABLE = 0x0001
DEVICE_CAMERA = 0x0002

COMMAND_TURNTABLE_ENABLE = 0x0001
COMMAND_TURNTABLE_POSITION = 0x0002
COMMAND_TURNTABLE_JOG = 0x0003
COMMAND_TURNTABLE_SPEED = 0x0004
COMMAND_CAMERA_LASER_STANDBY = 0x0101
COMMAND_CAMERA_LASER_SINGLE_MEASURE = 0x0102
COMMAND_CAMERA_LASER_CONTINUOUS_MEASURE = 0x0103
COMMAND_CAMERA_LASER_SELF_TEST = 0x0104
COMMAND_CAMERA_LASER_SET_NEAREST_DISTANCE = 0x0105
COMMAND_CAMERA_LASER_QUERY_SHOT_COUNT = 0x0106
COMMAND_CAMERA_LASER_SET_FARTHEST_DISTANCE = 0x0107
COMMAND_CAMERA_LASER_APD_POWER_ON = 0x0108
COMMAND_CAMERA_LASER_APD_POWER_OFF = 0x0109
COMMAND_CAMERA_LASER_SET_WORK_TIMEOUT = 0x010A
COMMAND_CAMERA_LASER_QUERY_ID = 0x010B
COMMAND_CAMERA_LENS_ZOOM_IN = 0x0201
COMMAND_CAMERA_LENS_ZOOM_OUT = 0x0202
COMMAND_CAMERA_LENS_FOCUS_PLUS = 0x0203
COMMAND_CAMERA_LENS_FOCUS_MINUS = 0x0204
COMMAND_CAMERA_LENS_IRIS_PLUS = 0x0205
COMMAND_CAMERA_LENS_IRIS_MINUS = 0x0206
COMMAND_CAMERA_LENS_RELAY_ON = 0x0207
COMMAND_CAMERA_LENS_RELAY_OFF = 0x0208
COMMAND_CAMERA_LENS_SET_PRESET = 0x0209
COMMAND_CAMERA_LENS_CALL_PRESET = 0x020A
COMMAND_CAMERA_LENS_QUERY_ZOOM = 0x020B
COMMAND_CAMERA_LENS_QUERY_FOCUS = 0x020C
COMMAND_CAMERA_LENS_QUERY_IRIS = 0x020D
COMMAND_CAMERA_LENS_GOTO_ZOOM = 0x020E
COMMAND_CAMERA_LENS_GOTO_FOCUS = 0x020F
COMMAND_CAMERA_LENS_GOTO_IRIS = 0x0210
COMMAND_CAMERA_LENS_STOP = 0x0211
