/* Generated by scripts/generate_control_specs.py. Do not edit by hand. */
#ifndef MIDWARE_GENERATED_COMMANDS_H
#define MIDWARE_GENERATED_COMMANDS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MIDWARE_PARAM_UINT8 1
#define MIDWARE_PARAM_UINT16_BE 2
#define MIDWARE_PARAM_INT32_BE 3

#define MIDWARE_DEVICE_TURNTABLE 0x0001
#define MIDWARE_DEVICE_CAMERA 0x0002

#define MIDWARE_COMMAND_TURNTABLE_ENABLE 0x0001
#define MIDWARE_COMMAND_TURNTABLE_POSITION 0x0002
#define MIDWARE_COMMAND_TURNTABLE_JOG 0x0003
#define MIDWARE_COMMAND_TURNTABLE_SPEED 0x0004
#define MIDWARE_COMMAND_CAMERA_LASER_STANDBY 0x0101
#define MIDWARE_COMMAND_CAMERA_LASER_SINGLE_MEASURE 0x0102
#define MIDWARE_COMMAND_CAMERA_LASER_CONTINUOUS_MEASURE 0x0103
#define MIDWARE_COMMAND_CAMERA_LASER_SELF_TEST 0x0104
#define MIDWARE_COMMAND_CAMERA_LASER_SET_NEAREST_DISTANCE 0x0105
#define MIDWARE_COMMAND_CAMERA_LASER_QUERY_SHOT_COUNT 0x0106
#define MIDWARE_COMMAND_CAMERA_LASER_SET_FARTHEST_DISTANCE 0x0107
#define MIDWARE_COMMAND_CAMERA_LASER_APD_POWER_ON 0x0108
#define MIDWARE_COMMAND_CAMERA_LASER_APD_POWER_OFF 0x0109
#define MIDWARE_COMMAND_CAMERA_LASER_SET_WORK_TIMEOUT 0x010A
#define MIDWARE_COMMAND_CAMERA_LASER_QUERY_ID 0x010B
#define MIDWARE_COMMAND_CAMERA_LENS_ZOOM_IN 0x0201
#define MIDWARE_COMMAND_CAMERA_LENS_ZOOM_OUT 0x0202
#define MIDWARE_COMMAND_CAMERA_LENS_FOCUS_PLUS 0x0203
#define MIDWARE_COMMAND_CAMERA_LENS_FOCUS_MINUS 0x0204
#define MIDWARE_COMMAND_CAMERA_LENS_IRIS_PLUS 0x0205
#define MIDWARE_COMMAND_CAMERA_LENS_IRIS_MINUS 0x0206
#define MIDWARE_COMMAND_CAMERA_LENS_RELAY_ON 0x0207
#define MIDWARE_COMMAND_CAMERA_LENS_RELAY_OFF 0x0208
#define MIDWARE_COMMAND_CAMERA_LENS_SET_PRESET 0x0209
#define MIDWARE_COMMAND_CAMERA_LENS_CALL_PRESET 0x020A
#define MIDWARE_COMMAND_CAMERA_LENS_QUERY_ZOOM 0x020B
#define MIDWARE_COMMAND_CAMERA_LENS_QUERY_FOCUS 0x020C
#define MIDWARE_COMMAND_CAMERA_LENS_QUERY_IRIS 0x020D
#define MIDWARE_COMMAND_CAMERA_LENS_GOTO_ZOOM 0x020E
#define MIDWARE_COMMAND_CAMERA_LENS_GOTO_FOCUS 0x020F
#define MIDWARE_COMMAND_CAMERA_LENS_GOTO_IRIS 0x0210
#define MIDWARE_COMMAND_CAMERA_LENS_STOP 0x0211

typedef struct {
    const char* key;
    uint8_t type;
    int32_t min_value;
    int32_t max_value;
} midware_generated_param_spec_t;

typedef struct {
    uint16_t device_type;
    uint16_t command_type;
    const char* key;
    const midware_generated_param_spec_t* params;
    uint8_t param_count;
} midware_generated_command_spec_t;

static const midware_generated_param_spec_t midware_turntable_enable_params[] = {
    {"enabled", 1, 0, 0},
};
static const midware_generated_param_spec_t midware_turntable_position_params[] = {
    {"azimuth", 3, -360, 360},
    {"pitch", 3, -90, 90},
};
static const midware_generated_param_spec_t midware_turntable_jog_params[] = {
    {"azimuthDelta", 3, -360, 360},
    {"pitchDelta", 3, -360, 360},
};
static const midware_generated_param_spec_t midware_turntable_speed_params[] = {
    {"azimuthSpeed", 3, -838, 838},
    {"pitchSpeed", 3, -838, 838},
};

static const midware_generated_param_spec_t midware_camera_laser_continuous_measure_params[] = {
    {"periodMs", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_laser_set_nearest_distance_params[] = {
    {"distanceM", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_laser_set_farthest_distance_params[] = {
    {"distanceM", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_laser_set_work_timeout_params[] = {
    {"timeoutMin", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_lens_zoom_in_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_zoom_out_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_focus_plus_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_focus_minus_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_iris_plus_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_iris_minus_params[] = {
    {"speed", 1, 1, 63},
};
static const midware_generated_param_spec_t midware_camera_lens_relay_on_params[] = {
    {"relayId", 1, 1, 8},
};
static const midware_generated_param_spec_t midware_camera_lens_relay_off_params[] = {
    {"relayId", 1, 1, 8},
};
static const midware_generated_param_spec_t midware_camera_lens_set_preset_params[] = {
    {"presetId", 1, 1, 255},
};
static const midware_generated_param_spec_t midware_camera_lens_call_preset_params[] = {
    {"presetId", 1, 1, 255},
};
static const midware_generated_param_spec_t midware_camera_lens_goto_zoom_params[] = {
    {"position", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_lens_goto_focus_params[] = {
    {"position", 2, 0, 65535},
};
static const midware_generated_param_spec_t midware_camera_lens_goto_iris_params[] = {
    {"position", 2, 0, 65535},
};

static const midware_generated_command_spec_t MIDWARE_GENERATED_COMMAND_SPECS[] = {
    {0x0001, 0x0001, "enable", midware_turntable_enable_params, 1},
    {0x0001, 0x0002, "position", midware_turntable_position_params, 2},
    {0x0001, 0x0003, "jog", midware_turntable_jog_params, 2},
    {0x0001, 0x0004, "speed", midware_turntable_speed_params, 2},
    {0x0002, 0x0101, "laser_standby", 0, 0},
    {0x0002, 0x0102, "laser_single_measure", 0, 0},
    {0x0002, 0x0103, "laser_continuous_measure", midware_camera_laser_continuous_measure_params, 1},
    {0x0002, 0x0104, "laser_self_test", 0, 0},
    {0x0002, 0x0105, "laser_set_nearest_distance", midware_camera_laser_set_nearest_distance_params, 1},
    {0x0002, 0x0106, "laser_query_shot_count", 0, 0},
    {0x0002, 0x0107, "laser_set_farthest_distance", midware_camera_laser_set_farthest_distance_params, 1},
    {0x0002, 0x0108, "laser_apd_power_on", 0, 0},
    {0x0002, 0x0109, "laser_apd_power_off", 0, 0},
    {0x0002, 0x010A, "laser_set_work_timeout", midware_camera_laser_set_work_timeout_params, 1},
    {0x0002, 0x010B, "laser_query_id", 0, 0},
    {0x0002, 0x0201, "lens_zoom_in", midware_camera_lens_zoom_in_params, 1},
    {0x0002, 0x0202, "lens_zoom_out", midware_camera_lens_zoom_out_params, 1},
    {0x0002, 0x0203, "lens_focus_plus", midware_camera_lens_focus_plus_params, 1},
    {0x0002, 0x0204, "lens_focus_minus", midware_camera_lens_focus_minus_params, 1},
    {0x0002, 0x0205, "lens_iris_plus", midware_camera_lens_iris_plus_params, 1},
    {0x0002, 0x0206, "lens_iris_minus", midware_camera_lens_iris_minus_params, 1},
    {0x0002, 0x0207, "lens_relay_on", midware_camera_lens_relay_on_params, 1},
    {0x0002, 0x0208, "lens_relay_off", midware_camera_lens_relay_off_params, 1},
    {0x0002, 0x0209, "lens_set_preset", midware_camera_lens_set_preset_params, 1},
    {0x0002, 0x020A, "lens_call_preset", midware_camera_lens_call_preset_params, 1},
    {0x0002, 0x020B, "lens_query_zoom", 0, 0},
    {0x0002, 0x020C, "lens_query_focus", 0, 0},
    {0x0002, 0x020D, "lens_query_iris", 0, 0},
    {0x0002, 0x020E, "lens_goto_zoom", midware_camera_lens_goto_zoom_params, 1},
    {0x0002, 0x020F, "lens_goto_focus", midware_camera_lens_goto_focus_params, 1},
    {0x0002, 0x0210, "lens_goto_iris", midware_camera_lens_goto_iris_params, 1},
    {0x0002, 0x0211, "lens_stop", 0, 0},
};

#define MIDWARE_GENERATED_COMMAND_SPEC_COUNT \
    (sizeof(MIDWARE_GENERATED_COMMAND_SPECS) / sizeof(MIDWARE_GENERATED_COMMAND_SPECS[0]))

#ifdef __cplusplus
}
#endif

#endif
